using MockPaymentsAndSales.ReturnObjects;

namespace MockPaymentsAndSales.Gateways.Interfaces
{
    public interface ISalesGateway
    {
        /// <summary>
        /// This method returns sales generated by a LLM of choice.
        /// </summary>
        Task<IReadOnlyCollection<ReturnSale>> ReturnAllSales(int salesAmount, DateTime startTime, DateTime endTime);
    }
}
